# For full config options, check the docs:
#    docs.serverless.com
service: serverless-api-cars-swapi 

plugins:
  - serverless-plugin-typescript
  - serverless-stack-output
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:GetItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:Scan"
            Resource:
              - { "Fn::GetAtt": ["CarsTable", "Arn"] }  

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

resources:
  Resources:
      CarsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: CarsTable
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          AttributeDefinitions:
            - AttributeName: carID
              AttributeType: S
          KeySchema:
            - AttributeName: carID
              KeyType: HASH
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: HttpApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
functions:
  listNames:
      handler: src/functions/handlers.listNames
      events:
        - httpApi:
            path: /names
            method: get
  listPlanets:
      handler: src/functions/handlers.listPlanets
      events:
        - httpApi:
            path: /planets
            method: get         
  healthcheck:
      handler: src/functions/healthcheck.healthcheck
      description: Healthcheck to ensure the service is up
      events:
        - httpApi:
            path: /healthcheck
            method: get
  createCar:
      handler: src/functions/handlers.createCar       
      events:
        - httpApi:
            path: /car
            method: post     
  getAllCars:
      handler: src/functions/handlers.getAllCars       
      events:
        - httpApi:
            path: /carList
            method: get   